language: r
sudo: false
cache: packages

warnings_are_errors: true

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: never
    on_failure: change

env:
  - global:
      - NOT_CRAN=true
