language: r
sudo: false
cache: packages

r:
  - release
  - devel

r_github_packages:
  - statnet/statnet.common
  - statnet/network
  - statnet/ergm

warnings_are_errors: true

notifications:
  email:
    on_success: never
    on_failure: change
  slack: epimodel:ARrkdZn2p9KKRZxkcGFK9Ns0
