language: r
sudo: false
cache: packages

r:
  - release
  - devel

r_github_packages:
  - statnet/statnet.common
  - statnet/network
  - statnet/ergm

warnings_are_errors: true

notifications:
  email: false
  slack: epimodel:iY6F3MeHlZ2LCM4MwuVRJj7D
