environment:
  R_CHECK_ARGS: --no-build-vignettes --no-manual

install:
  ps: Bootstrap

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs
